Allow empty subject on CSR creation if SAN is present

diff --git a/bin/nanoca b/bin/nanoca
--- a/bin/nanoca
+++ b/bin/nanoca
@@ -22,7 +22,7 @@
 # Requires bash >= 4, openssl >= 1.0.1e, awk, ls, cat and wc.
 #
 # Created: 2020-07-10
-# Updated: 2026-02-18
+# Updated: 2026-02-26
 #
 # TODO:
 #  - Take care of stderr from openssl and print that on error
@@ -460,8 +460,7 @@ function create_request() {
     if [[ "${req_type}" == "machine" ]] ; then
         # Request for machine certificate
         # Collect Subject attributes from user
-        echo "Enter Subject (the CN attribute is mandatory, others can"
-        echo "be left out by entering a empty value):"
+        echo "Enter Subject (leve blank to exclude):"
         read -e -i "${csr_c}"  -p "ISO 3166-1 alpha-2 Country Code, C: " csr_c
         read -e -i "${csr_st}" -p "State or Province, ST: " csr_st
         read -e -i "${csr_l}"  -p "Location or City, L: " csr_l
@@ -469,13 +468,7 @@ function create_request() {
         read -e -i "${csr_ou}" -p "Organizational Unit, OU: " csr_ou
         read -e -i "${csr_cn}" -p "Common Name, CN: " csr_cn
 
-        # Verify that the CN is not empty
-        if [[ -z "${csr_cn}" ]] ; then
-            echo "Error: Common Name (CN) can not be empty." >&2
-            return 1
-        fi
-
-       # Get Extended Key Usage settings from the user
+        # Get Extended Key Usage settings from the user
         if yesanswer "Yes" "Should the cert be used for TLS server auth" ; then
             csr_eku="${csr_eku}${csr_eku:+,}serverAuth"
 
@@ -491,6 +484,11 @@ function create_request() {
 
         # Collect SAN from the user
         read -e -p "Space separated list of SAN (DNS name or IPv4-address) to be added: " user_sans
+
+        if [[ -z "${user_sans}" && -z "${csr_cn}" ]] ; then
+            echo "Error: SAN can not be empty if CN is empty." >&2
+            return 1
+        fi
 
         # Add user supplied SANs to the san list. Make sure to not get the CN
         # twice if the user enters the CN as SAN
@@ -585,6 +583,9 @@ function create_request() {
     [[ -n "${csr_cn}" ]]    && csr_subject="${csr_subject}/CN=${csr_cn}"
     [[ -n "${csr_email}" ]] && csr_subject="${csr_subject}/emailAddress=${csr_email}"
     [[ -n "${csr_uid}" ]]   && csr_subject="${csr_subject}/UID=${csr_uid}"
+    if [[ -z "${csr_subject}" ]] ; then
+        csr_subject="/"
+    fi
 
     echo ""
     echo "You are about to create a CSR using the following parameters:"
