Make CA lifespan configurable

diff --git a/bin/nanoca b/bin/nanoca
--- a/bin/nanoca
+++ b/bin/nanoca
@@ -46,7 +46,7 @@ declare -r OPENSSL="/usr/bin/openssl"
 declare -r AWK="/usr/bin/awk"
 
 # CA lifespan defaults (20 years)
-declare -ir CA_DAYS_DEFAULT=7300
+declare -ir CA_YEARS_DEFAULT=20
 
 # CA RSA key size defaults (2048 bits)
 declare -ir CA_RSA_KEYSIZE_DEFAULT=2048
@@ -217,14 +217,15 @@ function create_ca() {
     local ca_o=""
     local ca_ou=""
     local ca_cn=""
-    local ca_days="${CA_DAYS}"
-    local ca_rsa_keysize="${CA_RSA_KEYSIZE}"
+    local -i ca_years=${CA_YEARS}
+    local -i ca_days=""
+    local -i ca_rsa_keysize=${CA_RSA_KEYSIZE}
     local ca_rsa_ssa="${CA_RSA_SSA}"
     local ca_key_pw_protected="${CA_KEY_PW_PROTECTED}"
     local ca_rsa_padding_mode=""
     local ca_rsa_pss_saltlen=""
-    local ca_signed_cert_days="${CA_SIGNED_CERT_DAYS}"
-    local crl_days="${CA_CRL_DAYS}"
+    local -i ca_signed_cert_days=${CA_SIGNED_CERT_DAYS}
+    local -i crl_days=${CA_CRL_DAYS}
     local ret=""
 
     # Verify that the directory for the new CA exists and is empty
@@ -251,7 +252,7 @@ function create_ca() {
     # We have some strict requirements on the CN attribute since
     # it is used in the file names for the CA certificate and key
     if [[ -z "${ca_cn}" || ! "${ca_cn}" =~ ^[a-zA-Z0-9\ \-]+$ ]] ; then
-        echo "Error: Common Name for the CA must be non-empty and must satisfy ^[a-zA-Z0-9 -]\$." >&2
+        echo "Error: Common Name for the CA must be non-empty and must satisfy ^[a-zA-Z0-9 -]+\$." >&2
         return 1
     fi
 
@@ -276,8 +277,9 @@ function create_ca() {
     fi
 
     echo "Enter CA lifespan settings:"
+    read -e -i "${ca_years}"            -p "CA lifespan (years): " ca_years
     read -e -i "${ca_signed_cert_days}" -p "Signed certificate lifespan (days): " ca_signed_cert_days
-    read -e -i "${crl_days}" -p "CRL lifespan (days): " crl_days
+    read -e -i "${crl_days}"            -p "CRL lifespan (days): " crl_days
 
     # Build CA subject string
     local ca_subject=""
@@ -364,6 +366,8 @@ function create_ca() {
         ca_rsa_padding_mode=""
         ca_rsa_pss_saltlen=""
     fi
+
+   let ca_days="ca_years*365"
 
     ${OPENSSL} req \
         -config "${openssl_cfg}" \
@@ -1109,7 +1113,7 @@ if [[ -f "${ca_path}/private/settings.cfg" ]] ; then
 fi
 
 # Initialize variables from defaults if not set from settings.cfg or environment
-CA_DAYS="${CA_DAYS:-${CA_DAYS_DEFAULT}}"
+CA_YEARS="${CA_YEARS:-${CA_YEARS_DEFAULT}}"
 CA_RSA_KEYSIZE="${CA_RSA_KEYSIZE:-${CA_RSA_KEYSIZE_DEFAULT}}"
 CA_KEY_PW_PROTECTED="${CA_KEY_PW_PROTECTED:-${CA_KEY_PW_PROTECTED_DEFAULT}}"
 CA_RSA_SSA="${CA_RSA_SSA:-${CA_RSA_SSA_DEFAULT}}"
