Fix some variable assignments afte code review

diff --git a/bin/nanoca b/bin/nanoca
--- a/bin/nanoca
+++ b/bin/nanoca
@@ -73,7 +73,7 @@ declare -r CSR_RSA_SSA_DEFAULT="PKCS1-V1.5"
 # Global variable to hold "all yes" information
 declare -i all_yes
 
-# Global variable that hold the name of a temporary file
+# Global variable that holds the name of a temporary file
 declare openssl_cfg=""
 
 
@@ -425,7 +425,6 @@ function create_request() {
     local crt_key_pw_protected="${CERT_KEY_PW_PROTECTED}"
     local csr_rsa_padding_mode=""
     local csr_rsa_pss_saltlen=""
-    local res=""
     local ret=1
     local san_str=""
     local create_keyfile=1
@@ -463,7 +462,8 @@ function create_request() {
     echo "Choose request type:"
     echo "  1 - Request for machine certificate (server and/or client)"
     echo "  2 - Request for personal client certificate"
-    local req_type="$(choose_value 'Enter request type' '1' '1 2')"
+    local req_type
+    req_type=$(choose_value 'Enter request type' '1' '1 2')
 
     if [[ "${req_type}" == "1" ]] ; then
         req_type="machine"
@@ -767,7 +767,7 @@ function sign_request() {
     fi
 
     if ! ${OPENSSL} req -verify -noout -in "${in_csr}" 2>/dev/null ; then
-        echo "Error: File '${in_csr}' is not a valid CSR. " >&2
+        echo "Error: File '${in_csr}' is not a valid CSR." >&2
         return ${ret}
     fi
 
@@ -854,7 +854,8 @@ function sign_request() {
     # Check the CSR and if empty subject, synthesize a subject from SAN
     if [[ -z "$(${OPENSSL} req -noout -subject -in "${in_csr}" | sed 's/subject=//g')" ]] ; then
         # Extract CN from first SAN in csr
-        local first_san=$(${OPENSSL} req -noout -text -in "${in_csr}" | ${AWK} -F'DNS:' '/DNS:/ { sub(",", ""); print $2 }')
+	local first_san
+        first_san=$(${OPENSSL} req -noout -text -in "${in_csr}" | ${AWK} -F'DNS:' '/DNS:/ { sub(",", ""); print $2 }')
         synthesized_subj="/CN=${first_san}"
     fi
 
